package quevedo.hibernatetest;
// Generated 21-dic-2018 8:56:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ingredients generated by hbm2java
 */
@Entity
@Table(name="ingredients"
    
)
public class Ingredient  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<IngredientPotion> ingredientsPotionses = new HashSet<IngredientPotion>(0);

    public Ingredient() {
    }

	
    public Ingredient(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public Ingredient(String name, String description, Set<IngredientPotion> ingredientsPotionses) {
       this.name = name;
       this.description = description;
       this.ingredientsPotionses = ingredientsPotionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ingredients")
    public Set<IngredientPotion> getIngredientsPotionses() {
        return this.ingredientsPotionses;
    }
    
    public void setIngredientsPotionses(Set<IngredientPotion> ingredientsPotionses) {
        this.ingredientsPotionses = ingredientsPotionses;
    }

  @Override
  public String toString() {
    return "Ingredients{" + "id=" + id + ", name=" + name + ", description=" + description + '}';
  }




}


