package quevedo.hibernatetest;
// Generated 21-dic-2018 8:56:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IngredientsPotionsId generated by hbm2java
 */
@Embeddable
public class IngredientPotionId  implements java.io.Serializable {


     private int idIngredient;
     private int idPotion;

    public IngredientPotionId() {
    }

    public IngredientPotionId(int idIngredient, int idPotion) {
       this.idIngredient = idIngredient;
       this.idPotion = idPotion;
    }
   


    @Column(name="id_ingredient", nullable=false)
    public int getIdIngredient() {
        return this.idIngredient;
    }
    
    public void setIdIngredient(int idIngredient) {
        this.idIngredient = idIngredient;
    }


    @Column(name="id_potion", nullable=false)
    public int getIdPotion() {
        return this.idPotion;
    }
    
    public void setIdPotion(int idPotion) {
        this.idPotion = idPotion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IngredientPotionId) ) return false;
		 IngredientPotionId castOther = ( IngredientPotionId ) other; 
         
		 return (this.getIdIngredient()==castOther.getIdIngredient())
 && (this.getIdPotion()==castOther.getIdPotion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIngredient();
         result = 37 * result + this.getIdPotion();
         return result;
   }   

  @Override
  public String toString() {
    return "IngredientsPotionsId{" + "idIngredient=" + idIngredient + ", idPotion=" + idPotion + '}';
  }


}


