package quevedo.hibernatetest;
// Generated 21-dic-2018 8:56:38 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IngredientsPotions generated by hbm2java
 */
@Entity
@Table(name="ingredients_potions"
   
)
public class IngredientPotion  implements java.io.Serializable {


     private IngredientPotionId id;
     private Ingredient ingredients;
     private Potion potions;
     private int cantidad;
     private String preparacion;
     private int orden;
     private int idIngPot;

    public IngredientPotion() {
    }

    public IngredientPotion(IngredientPotionId id, Ingredient ingredients, Potion potions, int cantidad, String preparacion, int orden, int idIngPot) {
       this.id = id;
       this.ingredients = ingredients;
       this.potions = potions;
       this.cantidad = cantidad;
       this.preparacion = preparacion;
       this.orden = orden;
       this.idIngPot = idIngPot;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idIngredient", column=@Column(name="id_ingredient", nullable=false) ), 
        @AttributeOverride(name="idPotion", column=@Column(name="id_potion", nullable=false) ) } )
    public IngredientPotionId getId() {
        return this.id;
    }
    
    public void setId(IngredientPotionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ingredient", nullable=false, insertable=false, updatable=false)
    public Ingredient getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Ingredient ingredients) {
        this.ingredients = ingredients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_potion", nullable=false, insertable=false, updatable=false)
    public Potion getPotions() {
        return this.potions;
    }
    
    public void setPotions(Potion potions) {
        this.potions = potions;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="preparacion", nullable=false, length=250)
    public String getPreparacion() {
        return this.preparacion;
    }
    
    public void setPreparacion(String preparacion) {
        this.preparacion = preparacion;
    }

    
    @Column(name="orden", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

    
    @Column(name="id_ing_pot", nullable=false)
    public int getIdIngPot() {
        return this.idIngPot;
    }
    
    public void setIdIngPot(int idIngPot) {
        this.idIngPot = idIngPot;
    }

  @Override
  public String toString() {
    return "IngredientsPotions{" + "id=" + id + ", ingredients=" + ingredients +  ", cantidad=" + cantidad + ", preparacion=" + preparacion + ", orden=" + orden + ", idIngPot=" + idIngPot + '}';
  }




}


