package quevedo.hibernatetest;
// Generated 21-dic-2018 8:56:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Potions generated by hbm2java
 */
@Entity
@Table(name="potions"
 
)
public class Potion  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Date creationDate;
     private int numberIngredients;
     private Set<IngredientPotion> ingredientsPotionses = new HashSet<IngredientPotion>(0);

    public Potion() {
    }

	
    public Potion(String name, String description, Date creationDate, int numberIngredients) {
        this.name = name;
        this.description = description;
        this.creationDate = creationDate;
        this.numberIngredients = numberIngredients;
    }
    public Potion(String name, String description, Date creationDate, int numberIngredients, Set<IngredientPotion> ingredientsPotionses) {
       this.name = name;
       this.description = description;
       this.creationDate = creationDate;
       this.numberIngredients = numberIngredients;
       this.ingredientsPotionses = ingredientsPotionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="number_ingredients", nullable=false)
    public int getNumberIngredients() {
        return this.numberIngredients;
    }
    
    public void setNumberIngredients(int numberIngredients) {
        this.numberIngredients = numberIngredients;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="potions")
    public Set<IngredientPotion> getIngredientsPotionses() {
        return this.ingredientsPotionses;
    }
    
    public void setIngredientsPotionses(Set<IngredientPotion> ingredientsPotionses) {
        this.ingredientsPotionses = ingredientsPotionses;
    }

  @Override
  public String toString() {
    return "Potions{" + "id=" + id + ", name=" + name + ", description=" + description + ", creationDate=" + creationDate + ", numberIngredients=" + numberIngredients + ", ingredientsPotionses=" + ingredientsPotionses + '}';
  }




}


